name: Build Kernel with KernelSU

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Adjust as needed

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libssl-dev make gcc clang llvm git wget ccache unzip libncurses-dev

    - name: Clone Kernel Source
      run: |
        git clone https://github.com/Darkstar085/kernel_oneplus_avicii.git kernel
        cd kernel
        git checkout fourteen  # Adjust the branch name if necessary

    - name: Clone KernelSU
      run: |
        git clone https://github.com/tiann/KernelSU.git kernel/KernelSU

    - name: Configure Kernel
      run: |
        cd kernel
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make avicii_defconfig  # Replace with the correct defconfig file for your device
        echo "CONFIG_KERNELSU=y" >> .config
        make olddefconfig

    - name: Build Kernel
      run: |
        cd kernel
        make -j$(nproc) CC=clang

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: kernel/arch/arm64/boot/Image.gz-dtb
