name: Push latest KernelSU Source

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"  # Run every Sunday at 9 AM IST (3:30 AM UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        submodules: recursive
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "King"
        git config user.email "king@gmail.com"

    - name: Sync KernelSU Repo
      run: |
        cd $GITHUB_WORKSPACE/KernelSU
        git checkout main
        git pull --ff-only
        cd ..
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "KernelSU: Sync with repo"
        fi

    - name: Push Changes
      if: ${{ github.ref_name == 'main' && env.ACCESS_TOKEN != '' }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN }}
